### ISSUE TITLE
animateContainerDuration Usage

### ISSUE THREAD

**Issue by flacial** [dgpedro/react-component-transition#3]
May I've an example of  the animateContainerDuration property?

**Comment by dgpedro** [comment]
Hi there!
Sure, [here](https://codesandbox.io/s/animatecontainerduration-bu63l?file=/src/App.js) you can find a simple example.

**Comment by flacial** [comment]
> Hi there!
> Sure, [here](https://codesandbox.io/s/animatecontainerduration-bu63l?file=/src/App.js) you can find a simple example.

Thank you :)
