### ISSUE TITLE
Polyfills should be peerDependencies

### ISSUE THREAD

**Issue by mmmeff** [dgpedro/react-component-transition#4]
It's not ideal to force consumers to install polyfills that they may not need. Move from `dependencies` to `peerDependencies` and include installation instructions in Polyfilling documentation.

The polyfills you're using also use a non-MIT license which can cause installation problems for certain users whose employers have strict licensing limits.

**Comment by dgpedro** [comment]
Hi there.

This is my first package, so there are some things I'm still learning how to do :) but thanks a lot for pointing me in the right direction.

I'll include those changes in next release.

Cheers!

**Comment by mmmeff** [comment]
Hey thanks dude! I should say - this package looks incredible. It fills a very real need in the React community for a simple transition framework between components. Solutions like `react-transition-group` are daunting to newcomers and there's a very real lack of alternatives out there.

I mainly cut this issue because I was hoping to pick this library up for a project I'm working on right now but I'm unable to install it because of the w3c polyfills having a weird license. Dang company infosec policies :( 

If this is your first package, I can't wait to see what else you make. Cheers mate!
